AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Template for the Dwell Well E-commerce application. All microservices and API Gateway in a single stack.

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Architectures:
      - x86_64

Parameters:
  ProductsTableName:
    Type: String
    Description: Name of the DynamoDB table for products.
    Default: DwellWellProductsTable
  CartTableName:
    Type: String
    Description: Name of DynamoDB table for cart items
    Default: DwellWellCartTable
  FrontendUrl:
    Type: String
    Description: Frontend callback URL for the application
    Default: https://localhost:5173/

Resources:
  ############### COGNITO RESOURCES ###############
  # --- Cognito user pool and client pool ---
  DwellWellCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: DwellWellUserPool
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: true
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true
      UsernameAttributes: [email]
      AutoVerifiedAttributes: [email]
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  DwellWellCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref DwellWellCognitoUserPool
      ClientName: DwellWellWebAppClient
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - !Ref FrontendUrl
      LogoutURLs:
        - !Ref FrontendUrl
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        #        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  DwellWellIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: DwellWellIdentityPool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref DwellWellCognitoUserPoolClient
          ProviderName: !GetAtt DwellWellCognitoUserPool.ProviderName # Updated GetAtt

  # Cognito user Groups
  DwellWellAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: admin
      UserPoolId: !Ref DwellWellCognitoUserPool
      Precedence: 1

  DwellWellSubAdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: subAdmin
      UserPoolId: !Ref DwellWellCognitoUserPool
      Precedence: 2

  # IdentityPool Authentication Roles
  DwellWellIdentityPoolAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DwellWellAuthRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref DwellWellIdentityPool
              "ForAnyValue:StringLike":
                cognito-identity.amazonaws.com:amr: authenticated
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonCognitoReadOnly
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  DwellWellIdentityPoolUnauthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DwellWellUnauthorizeRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref DwellWellIdentityPool
              "ForAnyValue:StringLike":
                cognito-identity.amazonaws.com:amr: unauthenticated
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonCognitoReadOnly



  ############### API GATEWAY RESOURCE ###############
  DwellWellApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true
      Cors:
        AllowMethods: \""GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt DwellWellCognitoUserPool.Arn # Updated GetAtt


  ############### EVENT BUS RESOURCE ###############
  DwellWellAppEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: DwellWellAppEventBus

  DwellWellEventBusPutEventsPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref DwellWellAppEventBus
      StatementId: AllowPutEventsFromAccount
      Action: events:PutEvents
      Principal: "*"


  ############### SES AND SNS RESOURCES ###############
  # SES Configuration for Email Notifications
  DwellWellSESConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: dwell-well-notifications

  DwellWellSESIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: noreply@dwell-well.com
      ConfigurationSetAttributes:
        ConfigurationSetName: !Ref DwellWellSESConfigurationSet

  # SNS Topics for notifications (UPDATED FOR DOMAIN SEPARATION)
  DwellWellOrderEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "DwellWellOrderEvents"
      DisplayName: "E-commerce Order Events"

  DwellWellInventoryEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "DwellWellInventoryEvents"
      DisplayName: "E-commerce Inventory Events"

  DwellWellPaymentEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "DwellWellPaymentEvents"
      DisplayName: "E-commerce Payment Events"

  DwellWellUserEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "DwellWellUserEvents"
      DisplayName: "E-commerce User Events"


  ############### DYNAMODB RESOURCES ###############
  # --- Products table resource ---
  DwellWellProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ProductsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sku
          AttributeType: S
        - AttributeName: productStatus
          AttributeType: S
        - AttributeName: price
          AttributeType: N
      KeySchema:
        - AttributeName: sku
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: DwellWellStatusPriceIndex
          KeySchema:
            - AttributeName: productStatus
              KeyType: HASH
            - AttributeName: price
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY

  # --- Cart Table ---
  DwellWellCartTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref CartTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: sku
          AttributeType: S
        - AttributeName: addedAt
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: sku
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: DwellWellSkuIndex
          KeySchema:
            - AttributeName: sku
              KeyType: HASH
            - AttributeName: addedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

############### LAMBDA FUNCTION RESOURCES ###############
  # --- Admin User Invitation Function ---
  DwellWellInviteUserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../cmd/invite-user/
      Handler: invite-user
      Runtime: provided.al2023
      Environment:
        Variables:
          USER_POOL_ID: !Ref DwellWellCognitoUserPool
      Policies:
        - Statement:
            Sid: CognitoAdminActions
            Effect: Allow
            Action:
              - cognito-idp:AdminCreateUser
              - cognito-idp:AdminAddUserToGroup
              - cognito-idp:AdminSetUserPassword
            Resource: !GetAtt DwellWellCognitoUserPool.Arn
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiInviteUser:
          Type: Api
          Properties:
            RestApiId: !Ref DwellWellApiGateway
            Path: api/admin/invite
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  # --- Products Function ---
  DwellWellGetProductsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../cmd/get-products/
      Handler: get-products
      Runtime: provided.al2023
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTableName
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiProducts:
          Type: Api
          Properties:
            RestApiId: !Ref DwellWellApiGateway
            Path: api/products/
            Method: POST
            Auth:
              Authorizer: NONE

  DwellWellGetSKUsByPriceFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../cmd/skus-by-price/
      Handler: skus-by-price
      Runtime: provided.al2023
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
      Policies:
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiSkus:
          Type: Api
          Properties:
            RestApiId: !Ref DwellWellApiGateway
            Path: api/products/skus-by-price
            Method: GET

  # --- Webhooks Functions ---
  DwellWellStrapiWebhookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../cmd/webhook-strapi/
      Handler: webhook-strapi
      Runtime: provided.al2023
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTableName
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiWebhookStrapi:
          Type: Api
          Properties:
            RestApiId: !Ref DwellWellApiGateway
            Path: api/webhooks/strapi
            Method: POST

  #  PaystackWebhookLambda:
  #    Type: AWS::Serverless::Function
  #    Metadata:
  #      BuildMethod: go1.x
  #    Properties:
  #      CodeUri: ../cmd/webhook-paystack/
  #      Handler: webhook-paystack
  #      Runtime: provided.al2023
  #      Environment:
  #        Variables:
  #          EVENT_BUS_NAME: !Ref DwellWellAppEventBus
  #      Policies:
  #        - EventBridgePutEventsPolicy:
  #            EventBusName: !Ref DwellWellAppEventBus
  #        - AWSXrayWriteOnlyAccess
  #        - CloudWatchLogsFullAccess
  #      Events:
  #        ApiWebhookPaystack:
  #          Type: Api
  #          Properties:
  #            RestApiId: !Ref DwellWellApiGateway
  #            Path: /webhooks/paystack
  #            Method: POST


  # --- Optional / Future Stacks ---
  # PaymentsStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/payments.yaml
  #     Parameters:
  #       ProductsTableName: !Ref ProductsTableName

  # OrdersStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/orders.yaml
  #     Parameters:
  #       AppEventBusName: !Ref DwellWellAppEventBus
  #       ProductsTableName: !Ref ProductsTableName

  # RatingsStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/ratings.yaml
  #     Parameters:
  #       AppEventBusName: !Ref DwellWellAppEventBus
  #       ProductsTableName: !Ref ProductsTableName

Outputs:
  ApiGatewayId:
    Value: !Ref DwellWellApiGateway
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${DwellWellApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AppEventBusName:
    Value: !Ref DwellWellAppEventBus
  DwellWellOrderEventsTopicArn:
    Description: ARN of the Order Events SNS Topic
    Value: !Ref DwellWellOrderEventsTopic
  DwellWellInventoryEventsTopicArn:
    Description: ARN of the Inventory Events SNS Topic
    Value: !Ref DwellWellInventoryEventsTopic
  DwellWellPaymentEventsTopicArn:
    Description: ARN of the Payment Events SNS Topic
    Value: !Ref DwellWellPaymentEventsTopic
  DwellWellUserEventsTopicArn:
    Description: ARN of the User Events SNS Topic
    Value: !Ref DwellWellUserEventsTopic