AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for the Dwell Well E-commerce application. Orchestrates nested stacks for each microservice.

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Architectures:
      - x86_64
    
Resources:
  # --- Authentication Stack ---
  AuthStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./stacks/auth.yaml

  # --- Payments Stack ---
  # PaymentsStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/payments.yaml
  #     Parameters:
  #       ProductsTableName: !GetAtt ProductsStack.Outputs.ProductsTableName

  # --- Core Infrastructure Stack (API Gateway + EventBus) ---
  CoreStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./stacks/core.yaml
      Parameters:
        CognitoUserPoolArn: !GetAtt AuthStack.Outputs.CognitoUserPoolArn
        # PaymentsLambdaArn: !GetAtt PaymentsStack.Outputs.PaymentsLambdaArn

  # --- Products Stack ---
  ProductsStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./stacks/products.yaml

  # --- Orders Stack ---
  # OrdersStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/orders.yaml
  #     Parameters:
  #       AppEventBusName: !GetAtt CoreStack.Outputs.AppEventBusName
  #       ProductsTableName: !GetAtt ProductsStack.Outputs.ProductsTableName

  # --- Ratings Stack ---
  # RatingsStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/ratings.yaml
  #     Parameters:
  #       AppEventBusName: !GetAtt CoreStack.Outputs.AppEventBusName
  #       ProductsTableName: !GetAtt ProductsStack.Outputs.ProductsTableName

  # --- Webhooks Stack ---
  WebhooksStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./stacks/webhooks.yaml
      Parameters:
        AppEventBusName: !GetAtt CoreStack.Outputs.AppEventBusName
        ProductsTableName: !GetAtt ProductsStack.Outputs.ProductsTableName

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !GetAtt CoreStack.Outputs.ApiEndpoint
  CognitoUserPoolId:
    Description: "The ID of the Cognito User Pool"
    Value: !GetAtt AuthStack.Outputs.CognitoUserPoolId
  CognitoUserPoolClientId:
    Description: "The ID of the Cognito User Pool Client"
    Value: !GetAtt AuthStack.Outputs.CognitoUserPoolClientId
