AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for the Dwell Well E-commerce application. All microservices and API Gateway in a single stack.

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Architectures:
      - x86_64

Parameters:
  CognitoUserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool for the authorizer.
  ProductsTableName:
    Type: String
    Description: Name of the DynamoDB table for products.

Resources:
  # --- API Gateway ---
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn

  # --- Event Bus ---
  AppEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: DwellWellAppEventBus

  EventBusPutEventsPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref AppEventBus
      StatementId: AllowPutEventsFromAccount
      Action: events:PutEvents
      Principal: "*"

  # --- Products Lambdas ---
  ProductsLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../cmd/
      Handler: products
      Runtime: provided.al2
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTableName
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiProducts:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /products/v1
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  SKUsByPriceLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../cmd/
      Handler: skus-by-price
      Runtime: provided.al2
      Policies:
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiSkus:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /products/v1/skus-by-price
            Method: GET

  # --- Webhooks Lambdas ---
  PaystackWebhookLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../cmd/
      Handler: webhook-paystack
      Runtime: provided.al2
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref AppEventBus
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref AppEventBus
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiWebhookPaystack:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /webhooks/v1/paystack
            Method: POST

  StrapiWebhookLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../cmd/
      Handler: webhook-strapi
      Runtime: provided.al2
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTableName
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiWebhookStrapi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /webhooks/v1/strapi
            Method: POST

  # --- Optional / Future Stacks ---
  # PaymentsStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/payments.yaml
  #     Parameters:
  #       ProductsTableName: !Ref ProductsTableName

  # OrdersStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/orders.yaml
  #     Parameters:
  #       AppEventBusName: !Ref AppEventBus
  #       ProductsTableName: !Ref ProductsTableName

  # RatingsStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/ratings.yaml
  #     Parameters:
  #       AppEventBusName: !Ref AppEventBus
  #       ProductsTableName: !Ref ProductsTableName

Outputs:
  ApiGatewayId:
    Value: !Ref ApiGateway
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AppEventBusName:
    Value: !Ref AppEventBus
