AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for the Dwell Well E-commerce application. All microservices and API Gateway in a single stack.

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Architectures:
      - x86_64

Parameters:
  ProductsTableName:
    Type: String
    Description: Name of the DynamoDB table for products.
    Default: DwellWellProductsTable
  CartTableName:
    Type: String
    Description: Name of DynamoDB table for cart items
    Default: DwellWellCartTable

Resources:
# --- Cognito Resources ---
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: DwellWellUserPool
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true
      UsernameAttributes: [email]
      AutoVerifiedAttributes: [email]

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: DwellWellWebAppClient
      GenerateSecret: false

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: IncidentReportingIdentityPool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName

  # --- API Gateway ---
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      TracingEnabled: true
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn

  # --- Event Bus ---
  AppEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: DwellWellAppEventBus

  EventBusPutEventsPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref AppEventBus
      StatementId: AllowPutEventsFromAccount
      Action: events:PutEvents
      Principal: "*"

# --- Products table resource ---
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ProductsTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sku
          AttributeType: S
        - AttributeName: productStatus
          AttributeType: S
        - AttributeName: price
          AttributeType: N
      KeySchema:
        - AttributeName: sku
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: StatusPriceIndex
          KeySchema:
            - AttributeName: productStatus
              KeyType: HASH
            - AttributeName: price
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY

  # --- Cart Table ---
  CartTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref CartTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: sku
          AttributeType: S
        - AttributeName: addedAt
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: sku
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: skuIndex
          KeySchema:
            - AttributeName: sku
              KeyType: HASH
            - AttributeName: addedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

  # --- Products Function ---
  GetProductsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../cmd/get-products/
      Handler: get-products
      Runtime: provided.al2023
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTableName
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiProducts:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: api/products/
            Method: POST
            Auth:
                Authorizer: NONE

  GetSKUsByPriceFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../cmd/skus-by-price/
      Handler: skus-by-price
      Runtime: provided.al2023
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
      Policies:
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiSkus:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: api/products/skus-by-price
            Method: GET

  # --- Webhooks Functions ---
  StrapiWebhookFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../cmd/webhook-strapi/
      Handler: webhook-strapi
      Runtime: provided.al2023
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTableName
        - AWSXrayWriteOnlyAccess
        - CloudWatchLogsFullAccess
      Events:
        ApiWebhookStrapi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: api/webhooks/strapi
            Method: POST

#  PaystackWebhookLambda:
#    Type: AWS::Serverless::Function
#    Metadata:
#      BuildMethod: go1.x
#    Properties:
#      CodeUri: ../cmd/webhook-paystack/
#      Handler: webhook-paystack
#      Runtime: provided.al2023
#      Environment:
#        Variables:
#          EVENT_BUS_NAME: !Ref AppEventBus
#      Policies:
#        - EventBridgePutEventsPolicy:
#            EventBusName: !Ref AppEventBus
#        - AWSXrayWriteOnlyAccess
#        - CloudWatchLogsFullAccess
#      Events:
#        ApiWebhookPaystack:
#          Type: Api
#          Properties:
#            RestApiId: !Ref ApiGateway
#            Path: /webhooks/paystack
#            Method: POST


  # --- Optional / Future Stacks ---
  # PaymentsStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/payments.yaml
  #     Parameters:
  #       ProductsTableName: !Ref ProductsTableName

  # OrdersStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/orders.yaml
  #     Parameters:
  #       AppEventBusName: !Ref AppEventBus
  #       ProductsTableName: !Ref ProductsTableName

  # RatingsStack:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./stacks/ratings.yaml
  #     Parameters:
  #       AppEventBusName: !Ref AppEventBus
  #       ProductsTableName: !Ref ProductsTableName

Outputs:
  ApiGatewayId:
    Value: !Ref ApiGateway
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  AppEventBusName:
    Value: !Ref AppEventBus
