AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authentication resources including Cognito User Pool with a strong password policy, MFA, and a post-confirmation trigger.

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: DwellWellUserPool
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true
      UsernameAttributes: [email]
      AutoVerifiedAttributes: [email]

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: DwellWellWebAppClient
      GenerateSecret: false

  PostConfirmationFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../../cmd/
      Handler: post-confirmation
      Runtime: provided.al2023
      Events:
        CognitoEvent: { Type: Cognito, Properties: { UserPool: !Ref CognitoUserPool, Trigger: PostConfirmation } }
    Policies:
      - AWSLambdaBasicExecutionRole
      - DynamoDBWritePolicy:
          TableName: '*'  
      - Statement:
          - Effect: Allow
            Action:
              - cognito-idp:AdminUpdateUserAttributes
              - cognito-idp:AdminAddUserToGroup
            Resource: !GetAtt CognitoUserPool.Arn 

Outputs:
  CognitoUserPoolId:
    Value: !Ref CognitoUserPool
  CognitoUserPoolClientId:
    Value: !Ref CognitoUserPoolClient
  CognitoUserPoolArn:
    Value: !GetAtt CognitoUserPool.Arn

