AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Order-related resources with on-demand DB, tracing, and Dead Letter Queues for reliability.

Parameters:
  AppEventBusName: { Type: String }
  ProductsTableName: { Type: String }

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Orders
      PrimaryKey: { Name: orderId, Type: String }
      BillingMode: PAY_PER_REQUEST

  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/src/handlers/create-order/
      Handler: bootstrap
      Runtime: provided.al2
      Tracing: Active
      Environment:
        Variables:
          ORDERS_TABLE_NAME: !Ref OrdersTable
          EVENT_BUS_NAME: !Ref AppEventBusName
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref OrdersTable }
        - EventBridgePutEventsPolicy: { EventBusName: !Ref AppEventBusName }

Outputs:
  OrdersLambdaArn:
    Value: !GetAtt CreateOrderFunction.Arn
    Export:
      Name: OrdersLambdaArn
