AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Order-related resources with on-demand DB, tracing, and Dead Letter Queues for reliability.

Parameters:
  AppEventBusName: { Type: String }
  ProductsTableName: { Type: String }

Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Orders
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CreatedAtIndex
          KeySchema:
            - AttributeName: createdAt
              KeyType: HASH
          Projection:
            ProjectionType: ALL


  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/cmd/create-order/
      Handler: bootstrap
      Runtime: provided.al2
      Tracing: Active
      Environment:
        Variables:
          ORDERS_TABLE_NAME: !Ref OrdersTable
          EVENT_BUS_NAME: !Ref AppEventBusName
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref OrdersTable }
        - EventBridgePutEventsPolicy: { EventBusName: !Ref AppEventBusName }

Outputs:
  OrdersLambdaArn:
    Value: !GetAtt CreateOrderFunction.Arn
    Export:
      Name: OrdersLambdaArn
