AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Payment processing resources with secure secret management for Paystack integration.

Parameters:
  ProductsTableName: { Type: String }

Resources:
  InitializePaymentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../../../cmd/initialize-payment/
      Handler: initialize-payment
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
          PAYSTACK_SECRET_KEY: '{{resolve:ssm:/dwellwell/paystack/secretkey:1}}'
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref ProductsTableName }
        - Statement:
            - Effect: Allow
              Action: ['ssm:GetParameter']
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/dwellwell/paystack/secretkey'

Outputs:
  PaymentsLambdaArn:
    Value: !GetAtt InitializePaymentFunction.Arn
    Export:
      Name: PaymentsLambdaArn
