AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Product-related resources, including the on-demand database and public API endpoints.

Resources:
  ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Products
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: sku
            AttributeType: S
          - AttributeName: productStatus
            AttributeType: S
          - AttributeName: price
            AttributeType: N
        KeySchema:
          - AttributeName: sku
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StatusPriceIndex
            KeySchema:
              - AttributeName: productStatus
                KeyType: HASH
              - AttributeName: price
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY


  GetProductsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../../../cmd/get-products/
      Handler: get-products
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTable
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref ProductsTable }

  GetSKUsByPriceFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../../../cmd/get-skus-by-price/
      Handler: get-skus-by-price
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTable
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref ProductsTable }

Outputs:
  ProductsLambdaArn:
    Value: !GetAtt GetProductsFunction.Arn
    Export:
      Name: ProductsLambdaArn
  SKUsByPriceLambdaArn:
    Value: !GetAtt GetSKUsByPriceFunction.Arn
    Export:
      Name: SKUsByPriceLambdaArn
  ProductsTableName:
    Value: !Ref ProductsTable
