AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Product-related resources, including the on-demand database and public API endpoints.

Resources:
  ProductsOperationalTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: ProductsOperational
      PrimaryKey: { Name: sku, Type: String }
      BillingMode: PAY_PER_REQUEST

  GetProductsOperationalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/src/handlers/get-products-operational/
      Handler: bootstrap
      Runtime: provided.al2
      Tracing: Active
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsOperationalTable
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref ProductsOperationalTable }

  GetSKUsByPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/src/handlers/get-skus-by-price/
      Handler: bootstrap
      Runtime: provided.al2
      Tracing: Active
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsOperationalTable
      Policies:
        - DynamoDBReadPolicy: { TableName: !Ref ProductsOperationalTable }

Outputs:
  ProductsOperationalLambdaArn:
    Value: !GetAtt GetProductsOperationalFunction.Arn
    Export:
      Name: ProductsOperationalLambdaArn
  SKUsByPriceLambdaArn:
    Value: !GetAtt GetSKUsByPriceFunction.Arn
    Export:
      Name: SKUsByPriceLambdaArn
  ProductsOperationalTableName:
    Value: !Ref ProductsOperationalTable
