AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resources for managing product ratings.

Parameters:
  ApiGatewayId: { Type: String }
  CognitoAuthorizerId: { Type: String }
  AppEventBusName: { Type: String }
  ProductsTableName: { Type: String }

Resources:
  ProductRatingsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: ProductRatings
      PrimaryKey: { Name: productId, Type: String }
      ProvisionedThroughput: { ReadCapacityUnits: 5, WriteCapacityUnits: 5 }

  SubmitRatingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/src/handlers/submit-rating/
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        ApiEvent: { Type: Api, Properties: { RestApiId: !Ref ApiGatewayId, Path: /ratings, Method: post, Auth: { Authorizer: !Ref CognitoAuthorizerId } } }
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref ProductRatingsTable }
        - EventBridgePutEventsPolicy: { EventBusName: !Ref AppEventBusName }

  UpdateAverageRatingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/src/handlers/update-average-rating/
      Handler: bootstrap
      Runtime: provided.al2
      Events:
        RatingSubmittedEvent: { Type: EventBridgeRule, Properties: { EventBusName: !Ref AppEventBusName, Pattern: { source: ["app.ratings"], "detail-type": ["RatingSubmitted"] } } }
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref ProductsTableName }
        - DynamoDBReadPolicy: { TableName: !Ref ProductRatingsTable }
