AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resources for managing product ratings with on-demand DB, tracing, and DLQs.

Parameters:
  AppEventBusName: { Type: String }
  ProductsTableName: { Type: String }

Resources:
  ProductRatingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProductRatings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
        - AttributeName: rating
          AttributeType: N
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: RatingIndex
          KeySchema:
            - AttributeName: rating
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  SubmitRatingFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../../../cmd/submit-rating/
      Handler: submit-rating
      Environment:
        Variables:
          RATINGS_TABLE_NAME: !Ref ProductRatingsTable
          EVENT_BUS_NAME: !Ref AppEventBusName
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref ProductRatingsTable }
        - EventBridgePutEventsPolicy: { EventBusName: !Ref AppEventBusName }

  UpdateRatingDLQ:
    Type: AWS::SQS::Queue

  UpdateAverageRatingFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../../../cmd/update-average-rating/
      Handler: update-average-rating
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt UpdateRatingDLQ.Arn
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
          RATINGS_TABLE_NAME: !Ref ProductRatingsTable
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref ProductsTableName }
        - DynamoDBReadPolicy: { TableName: !Ref ProductRatingsTable }
        - SQSSendMessagePolicy: { QueueName: !GetAtt UpdateRatingDLQ.QueueName }

Outputs:
  RatingsLambdaArn:
    Value: !GetAtt SubmitRatingFunction.Arn
    Export:
      Name: RatingsLambdaArn
