AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resources for managing product ratings with on-demand DB, tracing, and DLQs.

Parameters:
  AppEventBusName: { Type: String }
  ProductsTableName: { Type: String }

Resources:
  ProductRatingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProductRatings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
        - AttributeName: rating
          AttributeType: N
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: RatingIndex
          KeySchema:
            - AttributeName: rating
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  SubmitRatingFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../../cmd/
      Handler: submit-rating
      Runtime: provided.al2023
      Environment:
        Variables:
          RATINGS_TABLE_NAME: !Ref ProductRatingsTable
          EVENT_BUS_NAME: !Ref AppEventBusName
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt ProductRatingsTable.Arn
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${AppEventBusName}'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 'arn:aws:logs:*:*:*'
            - Effect: Allow
              Action:
                - xray:PutTelemetryRecords
                - xray:PutTraceSegments
              Resource: '*'

  UpdateRatingDLQ:
    Type: AWS::SQS::Queue

  UpdateAverageRatingFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ../../cmd/
      Handler: update-average-rating
      Runtime: provided.al2023
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt UpdateRatingDLQ.Arn
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
          RATINGS_TABLE_NAME: !Ref ProductRatingsTable
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProductsTableName}'
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt ProductRatingsTable.Arn
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt UpdateRatingDLQ.Arn
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 'arn:aws:logs:*:*:*'
            - Effect: Allow
              Action:
                - xray:PutTelemetryRecords
                - xray:PutTraceSegments
              Resource: '*'

Outputs:
  RatingsLambdaArn:
    Description: "ARN of SubmitRating Lambda"
    Value: !GetAtt SubmitRatingFunction.Arn
    Export:
      Name: RatingsLambdaArn

  UpdateAverageRatingLambdaArn:
    Description: "ARN of UpdateAverageRating Lambda"
    Value: !GetAtt UpdateAverageRatingFunction.Arn
    Export:
      Name: UpdateAverageRatingLambdaArn

  ProductRatingsTableName:
    Description: "DynamoDB table name for product ratings"
    Value: !Ref ProductRatingsTable
    Export:
      Name: ProductRatingsTableName
