AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Resources for managing product ratings with on-demand DB, tracing, and DLQs.

Parameters:
  AppEventBusName: { Type: String }
  ProductsTableName: { Type: String }

Resources:
  ProductRatingsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: ProductRatings
      PrimaryKey: { Name: productId, Type: String }
      BillingMode: PAY_PER_REQUEST

  SubmitRatingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/src/handlers/submit-rating/
      Handler: bootstrap
      Runtime: provided.al2
      Tracing: Active
      Environment:
        Variables:
          RATINGS_TABLE_NAME: !Ref ProductRatingsTable
          EVENT_BUS_NAME: !Ref AppEventBusName
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref ProductRatingsTable }
        - EventBridgePutEventsPolicy: { EventBusName: !Ref AppEventBusName }

  UpdateRatingDLQ:
    Type: AWS::SQS::Queue

  UpdateAverageRatingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../backend/src/handlers/update-average-rating/
      Handler: bootstrap
      Runtime: provided.al2
      Tracing: Active
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt UpdateRatingDLQ.Arn
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTableName
          RATINGS_TABLE_NAME: !Ref ProductRatingsTable
      Policies:
        - DynamoDBCrudPolicy: { TableName: !Ref ProductsTableName }
        - DynamoDBReadPolicy: { TableName: !Ref ProductRatingsTable }
        - SQSSendMessagePolicy: { QueueName: !GetAtt UpdateRatingDLQ.QueueName }

Outputs:
  RatingsLambdaArn:
    Value: !GetAtt SubmitRatingFunction.Arn
    Export:
      Name: RatingsLambdaArn
