name: Build and Deploy SAM Application (DwellWell E-commerce App)

on:
  push:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

env:
  STACK_NAME: dwell-well-ecommerce-pr-${{ github.event.number }}  
  AWS_REGION: us-east-1
  S3_BUCKET: ${{ secrets.SAM_S3_BUCKET }}
  GO_VERSION: '1.25.3'

jobs:
  test:
    name: Run unit tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      # - name: Run tests
        # run: go test ./...

  deploy:
    if: github.event_name == 'pull_request' 
    needs: test
    name: Package & Deploy SAM
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.CFN_EXEC_ROLE }}

      - name: Build
        run: sam build --template infrastructure/template.yaml

      - name: Package
        run: |
          sam package \
            --template-file .aws-sam/build/template.yaml \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --output-template-file packaged.yaml

      - name: Deploy
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \
            --region ${{ env.AWS_REGION }}